### ISSUE TITLE
Using ORSSerialPort in a command line tool

### ISSUE THREAD

**Issue by ladislas** [armadsen/ORSSerialPort#113]
Hi there!

Based on your command line example, I've made a command line tool to test different arduino programs.

I installed the ORSSerialPort as a Xcode subproject following the [wiki](https://github.com/armadsen/ORSSerialPort/wiki/Installing-ORSSerialPort). When building inside of Xcode, everything works fine, but if I try to run the binaries from the command line, it fails saying it can't find the libraries.

[This issue](http://stackoverflow.com/questions/630911/using-frameworks-in-a-command-line-tool) on stackoverflow seems to say there is no solutions.

But i was wondering if you had any advice. 

Btw, doing it like you do in your examples works fine (adding the files by hand).

**Comment by armadsen** [comment]
Sorry it took so long to reply to this. The most upvoted answer in that Stack Overflow question is correct. You would have to put ORSSerial.framework in one of the standard system framework directories. You're probably better off including ORSSerialPort as source. Alternatively, you could do what the other answer mentions, which is to build a static library for ORSSerialPort instead of a dynamic framework, then link the static library into your command line program.
