### ISSUE TITLE
I would rather wait for all data to be sent before continuing with the next line of code

### ISSUE THREAD

**Issue by moyun-yinyun** [armadsen/ORSSerialPort#181]
i wan't sync write data how to set, Thank you!

**Comment by armadsen** [comment]
Sorry it took so long to get to your question. There isn't currently a way to do this, and I'm not likely to add it because it significantly complicates the API, and in general I don't think it makes sense to structure code this way. If you have control of the serial protocol, you're better off designing it so the device on the other end sends an acknowledgement of some sort, and you wait until you receive that to continue on with the next task rather than blocking waiting for the send to finish.

ORSSerialPort's [request/response API](https://github.com/armadsen/ORSSerialPort/wiki/Request-Response-API) will help you here.
