### ISSUE TITLE
Hex Received data is not continuous

### ISSUE THREAD

**Issue by sonwa** [armadsen/ORSSerialPort#186]
Hi,
Sometimes the received data is not continuous.

![image](https://user-images.githubusercontent.com/1425134/164977579-a3dd0868-31cd-4706-b71b-ba4702402a5e.png)

**Comment by sonwa** [comment]
Serial device data length is 5, and sometimes data is received separately. Not the complete received data.

**Comment by armadsen** [comment]
Hi @sonwa. This is expected behavior. The underlying serial port hardware, the driver, and ORSSerialPort itself have no way of knowing what "complete" means for your data. Serial data isn't intrinsically structured, it's just a stream of bytes delivered as the port receives them.

In order to help you solve this, ORSSerialPort includes a packet parsing API. You can find information about how to use it on this Wiki page: https://github.com/armadsen/ORSSerialPort/wiki/Packet-Parsing-API. Let me know if you have questions as you start using it.
