### ISSUE TITLE
Serial  Data in a Swift Playground

### ISSUE THREAD

**Issue by samuraipapa** [armadsen/ORSSerialPort#59]
This code is great. 

ORSSerial works in my OS X  app very well.   Any chance you'd write a port of ORSSerialPort's functionality into a Swift Playground?  For example, a "Hello World playground displaying a realtime serial data-stream".  That would be awesome. 

I'm trying to visually graph an incoming sensor value from Arduino's Analog Input Pin, in realtime. 
I'd be happy to fill-out the rest of the code (from a Hello-world Playground), to "live graph" in-coming serial data in a playground. 

Simply having an issue wrapping my head around getting live serial data into a Swift Playground...?

**Comment by armadsen** [comment]
I'm glad you're finding ORSSerialPort useful. Unfortunately, I don't think it's currently possible to use ORSSerialPort in a Swift playground because OS X Swift playgrounds are sandboxed, and the set of entitlements they get is not configurable. Network access is permitted, but other prohibited-by-default actions, including arbitrary file and serial port access are not. Sandboxed applications must declare the com.apple.security.device.serial entitlement in order to use ORSSerialPort.

I have filed [Radar #21677248](http://www.openradar.me/21677248) with Apple regarding this limitation. Feel free to file a duplicate with them if you'd like to add your voice.

You can download an example playground that should work if not for this limitation [here](https://www.dropbox.com/s/w49prikhuzkgjmc/SerialPlayground.zip?dl=0).

**Comment by samuraipapa** [comment]
Thanks for the info.  Great to know. 
Yes, I was able to replicate your error with your Playground file.  It looks like a great Playground btw.  When it works with ORSSerial, will be even better.  ; )

The Radar is a good idea.

**Comment by armadsen** [comment]
Since there's nothing I can do on this until/unless Apple addresses the underlying problem, I'm going to go ahead and close this. 

If Apple makes it possible, I will definitely add a playground to the ORSSerialPort examples.

**Comment by samuraipapa** [comment]
Perfect. Thanks for the help anyway.


On Sunday, July 5, 2015, Andrew Madsen <notifications@github.com> wrote:

> Since there's nothing I can do on this until/unless Apple addresses the
> underlying problem, I'm going to go ahead and close this.
>
> If Apple makes it possible, I will definitely add a playground to the
> ORSSerialPort examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armadsen/ORSSerialPort/issues/59#issuecomment-118699599>
> .
>


-- 
--------------------------------
Yury Gitman
Direct: (646) 263-5554
--------------------------------
--
